### ISSUE TITLE
infografia-alvaro froylan pacheco 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Alvaro2-0#1]
[Infografia_alvaro.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Alvaro2-0/files/15299692/Infografia_alvaro.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 19
